library:
  source-dirs: src
tests:
  Backup-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Backup
copyright: Copyright (c) Paul Gardiner
maintainer: haskell@glidos.net
dependencies:
- unix-time
- convertible
- unix
- directory-tree
- bytestring
- http-conduit
- http-client
- regex-posix
- regex-compat
- cond
- filepath
- directory
- time
- extra
- typed-process
- base >= 4.7 && < 5
- safe
name: Backup
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Paul Gardiner
github: Glidos/Backup
license: BSD3
executables:
  Backup-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Backup
description: Please see the README on GitHub at <https://github.com/Glidos/Backup#readme>
